[package]
name = "shev-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
